---
name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

.matrix:
  pkg:
    - name: Example
      repo: https://github.com/JuliaLang/Example.jl
  version:
    - "1.6"
    - "1"
  os:
    - ubuntu-latest
    - macos-latest-large
    - macos-latest-xlarge  # Apple silicon: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
  arch:
    - x86
    - x64
    - aarch64
  exclude:
    - os: ubuntu-latest
      arch: aarch64
    - os: macos-latest-large
      arch: x86
    - os: macos-latest-large
      arch: aarch64
    - os: macos-latest-xlarge
      arch: x86
    - os: macos-latest-xlarge
      arch: x64

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 2000

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"

  test-concept:
    name: Test ${{ matrix.pkg.name }} / Julia ${{ matrix.version }} (${{ matrix.os }}, ${{ matrix.arch }})
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     <<: *matrix
    steps:
      - run: exit 0
